<script src="js/jquery-2.1.4.min.js"></script>
<script src="<?php echo $t_path;?>js/isotope.min.js"></script>
<script src="<?php echo $t_path;?>js/ytplayer.min.js"></script>
<script src="<?php echo $t_path;?>js/owl.carousel.min.js"></script>
<script src="<?php echo $t_path;?>js/lightbox.min.js"></script>
<script src="<?php echo $t_path;?>js/smooth-scroll.min.js"></script>
<script src="<?php echo $t_path;?>js/scrollreveal.min.js"></script>
<script src="<?php echo $t_path;?>js/parallax.js"></script>
<script src="<?php echo $t_path;?>js/common.js"></script>